// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudMonitoringDashboardV1
import GoogleCloudWKT

func sample(client: DashboardsServiceClient, projectId: String, dashboardId: String) async throws {
  let response = try await client.updateDashboard(
    request: UpdateDashboardRequest()
      .with {
        $0.dashboard = Dashboard().with {
          $0.name = "projects/\(projectId)/dashboards/\(dashboardId)"
        }
      }
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudMonitoringDashboardV1.DashboardsServiceClient()
      try await sample(client: client, projectId: "[placeholder]", dashboardId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
