// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A widget that displays textual content.
public struct Text: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The text content to be displayed.
  public var content: Swift.String = Swift.String()

  /// How the text content is formatted.
  public var format: Text.Format = Text.Format()

  /// How the text is styled
  public var style: Text.TextStyle? = nil

  /// Initialize a new instance of `Text`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Text().with { $0.content = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Properties that determine how the title and content are styled
  public struct TextStyle: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The background color as a hex string. "#RRGGBB" or "#RGB"
    public var backgroundColor: Swift.String = Swift.String()

    /// The text color as a hex string. "#RRGGBB" or "#RGB"
    public var textColor: Swift.String = Swift.String()

    /// The horizontal alignment of both the title and content
    public var horizontalAlignment: Text.TextStyle.HorizontalAlignment = Text.TextStyle
      .HorizontalAlignment()

    /// The vertical alignment of both the title and content
    public var verticalAlignment: Text.TextStyle.VerticalAlignment = Text.TextStyle
      .VerticalAlignment()

    /// The amount of padding around the widget
    public var padding: Text.TextStyle.PaddingSize = Text.TextStyle.PaddingSize()

    /// Font sizes for both the title and content. The title will still be larger
    /// relative to the content.
    public var fontSize: Text.TextStyle.FontSize = Text.TextStyle.FontSize()

    /// The pointer location for this widget (also sometimes called a "tail")
    public var pointerLocation: Text.TextStyle.PointerLocation = Text.TextStyle.PointerLocation()

    /// Initialize a new instance of `TextStyle`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TextStyle().with { $0.backgroundColor = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The horizontal alignment of both the title and content on a text widget
    public enum HorizontalAlignment: Codable, Equatable, Sendable {
      /// No horizontal alignment specified, will default to H_LEFT
      case unspecified
      /// Left-align
      case hLeft
      /// Center-align
      case hCenter
      /// Right-align
      case hRight
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .hLeft: return 1
        case .hCenter: return 2
        case .hRight: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "HORIZONTAL_ALIGNMENT_UNSPECIFIED"
        case .hLeft: return "H_LEFT"
        case .hCenter: return "H_CENTER"
        case .hRight: return "H_RIGHT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "HORIZONTAL_ALIGNMENT_UNSPECIFIED": self = .unspecified
        case "H_LEFT": self = .hLeft
        case "H_CENTER": self = .hCenter
        case "H_RIGHT": self = .hRight
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .hLeft
        case 2: self = .hCenter
        case 3: self = .hRight
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .hLeft: return try container.encode(1)
        case .hCenter: return try container.encode(2)
        case .hRight: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The vertical alignment of both the title and content on a text widget
    public enum VerticalAlignment: Codable, Equatable, Sendable {
      /// No vertical alignment specified, will default to V_TOP
      case unspecified
      /// Top-align
      case vTop
      /// Center-align
      case vCenter
      /// Bottom-align
      case vBottom
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .vTop: return 1
        case .vCenter: return 2
        case .vBottom: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "VERTICAL_ALIGNMENT_UNSPECIFIED"
        case .vTop: return "V_TOP"
        case .vCenter: return "V_CENTER"
        case .vBottom: return "V_BOTTOM"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "VERTICAL_ALIGNMENT_UNSPECIFIED": self = .unspecified
        case "V_TOP": self = .vTop
        case "V_CENTER": self = .vCenter
        case "V_BOTTOM": self = .vBottom
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .vTop
        case 2: self = .vCenter
        case 3: self = .vBottom
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .vTop: return try container.encode(1)
        case .vCenter: return try container.encode(2)
        case .vBottom: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Specifies padding size around a text widget
    public enum PaddingSize: Codable, Equatable, Sendable {
      /// No padding size specified, will default to P_EXTRA_SMALL
      case unspecified
      /// Extra small padding
      case pExtraSmall
      /// Small padding
      case pSmall
      /// Medium padding
      case pMedium
      /// Large padding
      case pLarge
      /// Extra large padding
      case pExtraLarge
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .pExtraSmall: return 1
        case .pSmall: return 2
        case .pMedium: return 3
        case .pLarge: return 4
        case .pExtraLarge: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "PADDING_SIZE_UNSPECIFIED"
        case .pExtraSmall: return "P_EXTRA_SMALL"
        case .pSmall: return "P_SMALL"
        case .pMedium: return "P_MEDIUM"
        case .pLarge: return "P_LARGE"
        case .pExtraLarge: return "P_EXTRA_LARGE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PADDING_SIZE_UNSPECIFIED": self = .unspecified
        case "P_EXTRA_SMALL": self = .pExtraSmall
        case "P_SMALL": self = .pSmall
        case "P_MEDIUM": self = .pMedium
        case "P_LARGE": self = .pLarge
        case "P_EXTRA_LARGE": self = .pExtraLarge
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .pExtraSmall
        case 2: self = .pSmall
        case 3: self = .pMedium
        case 4: self = .pLarge
        case 5: self = .pExtraLarge
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .pExtraSmall: return try container.encode(1)
        case .pSmall: return try container.encode(2)
        case .pMedium: return try container.encode(3)
        case .pLarge: return try container.encode(4)
        case .pExtraLarge: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Specifies a font size for the title and content of a text widget
    public enum FontSize: Codable, Equatable, Sendable {
      /// No font size specified, will default to FS_LARGE
      case unspecified
      /// Extra small font size
      case fsExtraSmall
      /// Small font size
      case fsSmall
      /// Medium font size
      case fsMedium
      /// Large font size
      case fsLarge
      /// Extra large font size
      case fsExtraLarge
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .fsExtraSmall: return 1
        case .fsSmall: return 2
        case .fsMedium: return 3
        case .fsLarge: return 4
        case .fsExtraLarge: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "FONT_SIZE_UNSPECIFIED"
        case .fsExtraSmall: return "FS_EXTRA_SMALL"
        case .fsSmall: return "FS_SMALL"
        case .fsMedium: return "FS_MEDIUM"
        case .fsLarge: return "FS_LARGE"
        case .fsExtraLarge: return "FS_EXTRA_LARGE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "FONT_SIZE_UNSPECIFIED": self = .unspecified
        case "FS_EXTRA_SMALL": self = .fsExtraSmall
        case "FS_SMALL": self = .fsSmall
        case "FS_MEDIUM": self = .fsMedium
        case "FS_LARGE": self = .fsLarge
        case "FS_EXTRA_LARGE": self = .fsExtraLarge
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .fsExtraSmall
        case 2: self = .fsSmall
        case 3: self = .fsMedium
        case 4: self = .fsLarge
        case 5: self = .fsExtraLarge
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .fsExtraSmall: return try container.encode(1)
        case .fsSmall: return try container.encode(2)
        case .fsMedium: return try container.encode(3)
        case .fsLarge: return try container.encode(4)
        case .fsExtraLarge: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Specifies where a visual pointer is placed on a text widget (also
    /// sometimes called a "tail")
    public enum PointerLocation: Codable, Equatable, Sendable {
      /// No visual pointer
      case unspecified
      /// Placed in the middle of the top of the widget
      case plTop
      /// Placed in the middle of the right side of the widget
      case plRight
      /// Placed in the middle of the bottom of the widget
      case plBottom
      /// Placed in the middle of the left side of the widget
      case plLeft
      /// Placed on the left side of the top of the widget
      case plTopLeft
      /// Placed on the right side of the top of the widget
      case plTopRight
      /// Placed on the top of the right side of the widget
      case plRightTop
      /// Placed on the bottom of the right side of the widget
      case plRightBottom
      /// Placed on the right side of the bottom of the widget
      case plBottomRight
      /// Placed on the left side of the bottom of the widget
      case plBottomLeft
      /// Placed on the bottom of the left side of the widget
      case plLeftBottom
      /// Placed on the top of the left side of the widget
      case plLeftTop
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .plTop: return 1
        case .plRight: return 2
        case .plBottom: return 3
        case .plLeft: return 4
        case .plTopLeft: return 5
        case .plTopRight: return 6
        case .plRightTop: return 7
        case .plRightBottom: return 8
        case .plBottomRight: return 9
        case .plBottomLeft: return 10
        case .plLeftBottom: return 11
        case .plLeftTop: return 12
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "POINTER_LOCATION_UNSPECIFIED"
        case .plTop: return "PL_TOP"
        case .plRight: return "PL_RIGHT"
        case .plBottom: return "PL_BOTTOM"
        case .plLeft: return "PL_LEFT"
        case .plTopLeft: return "PL_TOP_LEFT"
        case .plTopRight: return "PL_TOP_RIGHT"
        case .plRightTop: return "PL_RIGHT_TOP"
        case .plRightBottom: return "PL_RIGHT_BOTTOM"
        case .plBottomRight: return "PL_BOTTOM_RIGHT"
        case .plBottomLeft: return "PL_BOTTOM_LEFT"
        case .plLeftBottom: return "PL_LEFT_BOTTOM"
        case .plLeftTop: return "PL_LEFT_TOP"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "POINTER_LOCATION_UNSPECIFIED": self = .unspecified
        case "PL_TOP": self = .plTop
        case "PL_RIGHT": self = .plRight
        case "PL_BOTTOM": self = .plBottom
        case "PL_LEFT": self = .plLeft
        case "PL_TOP_LEFT": self = .plTopLeft
        case "PL_TOP_RIGHT": self = .plTopRight
        case "PL_RIGHT_TOP": self = .plRightTop
        case "PL_RIGHT_BOTTOM": self = .plRightBottom
        case "PL_BOTTOM_RIGHT": self = .plBottomRight
        case "PL_BOTTOM_LEFT": self = .plBottomLeft
        case "PL_LEFT_BOTTOM": self = .plLeftBottom
        case "PL_LEFT_TOP": self = .plLeftTop
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .plTop
        case 2: self = .plRight
        case 3: self = .plBottom
        case 4: self = .plLeft
        case 5: self = .plTopLeft
        case 6: self = .plTopRight
        case 7: self = .plRightTop
        case 8: self = .plRightBottom
        case 9: self = .plBottomRight
        case 10: self = .plBottomLeft
        case 11: self = .plLeftBottom
        case 12: self = .plLeftTop
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .plTop: return try container.encode(1)
        case .plRight: return try container.encode(2)
        case .plBottom: return try container.encode(3)
        case .plLeft: return try container.encode(4)
        case .plTopLeft: return try container.encode(5)
        case .plTopRight: return try container.encode(6)
        case .plRightTop: return try container.encode(7)
        case .plRightBottom: return try container.encode(8)
        case .plBottomRight: return try container.encode(9)
        case .plBottomLeft: return try container.encode(10)
        case .plLeftBottom: return try container.encode(11)
        case .plLeftTop: return try container.encode(12)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.Text.TextStyle"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The format type of the text content.
  public enum Format: Codable, Equatable, Sendable {
    /// Format is unspecified. Defaults to MARKDOWN.
    case unspecified
    /// The text contains Markdown formatting.
    case markdown
    /// The text contains no special formatting.
    case raw
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .markdown: return 1
      case .raw: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FORMAT_UNSPECIFIED"
      case .markdown: return "MARKDOWN"
      case .raw: return "RAW"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FORMAT_UNSPECIFIED": self = .unspecified
      case "MARKDOWN": self = .markdown
      case "RAW": self = .raw
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .markdown
      case 2: self = .raw
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .markdown: return try container.encode(1)
      case .raw: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.Text"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
