// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A table that displays time series data.
public struct TimeSeriesTable: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The data displayed in this table.
  public var dataSets: [TimeSeriesTable.TableDataSet] = []

  /// Optional. Store rendering strategy
  public var metricVisualization: TimeSeriesTable.MetricVisualization =
    TimeSeriesTable.MetricVisualization()

  /// Optional. The list of the persistent column settings for the table.
  public var columnSettings: [TimeSeriesTable.ColumnSettings] = []

  /// Initialize a new instance of `TimeSeriesTable`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeSeriesTable().with { $0.dataSets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Groups a time series query definition with table options.
  public struct TableDataSet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Fields for querying time series data from the
    /// Stackdriver metrics API.
    public var timeSeriesQuery: TimeSeriesQuery? = nil

    /// Optional. A template string for naming `TimeSeries` in the resulting data
    /// set. This should be a string with interpolations of the form
    /// `${label_name}`, which will resolve to the label's value i.e.
    /// "${resource.labels.project_id}."
    public var tableTemplate: Swift.String = Swift.String()

    /// Optional. The lower bound on data point frequency for this data set,
    /// implemented by specifying the minimum alignment period to use in a time
    /// series query For example, if the data is published once every 10 minutes,
    /// the `min_alignment_period` should be at least 10 minutes. It would not
    /// make sense to fetch and align data at one minute intervals.
    public var minAlignmentPeriod: GoogleCloudWkt.Duration? = nil

    /// Optional. Table display options for configuring how the table is
    /// rendered.
    public var tableDisplayOptions: TableDisplayOptions? = nil

    /// Initialize a new instance of `TableDataSet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TableDataSet().with { $0.timeSeriesQuery = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.TimeSeriesTable.TableDataSet"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The persistent settings for a table's columns.
  public struct ColumnSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The id of the column.
    public var column: Swift.String = Swift.String()

    /// Required. Whether the column should be visible on page load.
    public var visible: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `ColumnSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ColumnSettings().with { $0.column = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.TimeSeriesTable.ColumnSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Enum for metric metric_visualization
  public enum MetricVisualization: Codable, Equatable, Sendable {
    /// Unspecified state
    case unspecified
    /// Default text rendering
    case number
    /// Horizontal bar rendering
    case bar
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .number: return 1
      case .bar: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "METRIC_VISUALIZATION_UNSPECIFIED"
      case .number: return "NUMBER"
      case .bar: return "BAR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "METRIC_VISUALIZATION_UNSPECIFIED": self = .unspecified
      case "NUMBER": self = .number
      case "BAR": self = .bar
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .number
      case 2: self = .bar
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .number: return try container.encode(1)
      case .bar: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.TimeSeriesTable"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
