// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A chart that displays data on a 2D (X and Y axes) plane.
public struct XyChart: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The data displayed in this chart.
  public var dataSets: [XyChart.DataSet] = []

  /// The duration used to display a comparison chart. A comparison chart
  /// simultaneously shows values from two similar-length time periods
  /// (e.g., week-over-week metrics).
  /// The duration must be positive, and it can only be applied to charts with
  /// data sets of LINE plot type.
  public var timeshiftDuration: GoogleCloudWkt.Duration? = nil

  /// Threshold lines drawn horizontally across the chart.
  public var thresholds: [Threshold] = []

  /// The properties applied to the x-axis.
  public var xAxis: XyChart.Axis? = nil

  /// The properties applied to the y-axis.
  public var yAxis: XyChart.Axis? = nil

  /// The properties applied to the y2-axis.
  public var y2Axis: XyChart.Axis? = nil

  /// Display options for the chart.
  public var chartOptions: ChartOptions? = nil

  /// Initialize a new instance of `XyChart`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = XyChart().with { $0.dataSets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Groups a time series query definition with charting options.
  public struct DataSet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Fields for querying time series data from the
    /// Stackdriver metrics API.
    public var timeSeriesQuery: TimeSeriesQuery? = nil

    /// How this data should be plotted on the chart.
    public var plotType: XyChart.DataSet.PlotType = XyChart.DataSet.PlotType()

    /// A template string for naming `TimeSeries` in the resulting data set.
    /// This should be a string with interpolations of the form `${label_name}`,
    /// which will resolve to the label's value.
    public var legendTemplate: Swift.String = Swift.String()

    /// Optional. The lower bound on data point frequency for this data set,
    /// implemented by specifying the minimum alignment period to use in a time
    /// series query For example, if the data is published once every 10 minutes,
    /// the `min_alignment_period` should be at least 10 minutes. It would not
    /// make sense to fetch and align data at one minute intervals.
    public var minAlignmentPeriod: GoogleCloudWkt.Duration? = nil

    /// Optional. The target axis to use for plotting the metric.
    public var targetAxis: XyChart.DataSet.TargetAxis = XyChart.DataSet.TargetAxis()

    /// Initialize a new instance of `DataSet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DataSet().with { $0.timeSeriesQuery = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The types of plotting strategies for data sets.
    public enum PlotType: Codable, Equatable, Sendable {
      /// Plot type is unspecified. The view will default to `LINE`.
      case unspecified
      /// The data is plotted as a set of lines (one line per series).
      case line
      /// The data is plotted as a set of filled areas (one area per series),
      /// with the areas stacked vertically (the base of each area is the top of
      /// its predecessor, and the base of the first area is the x-axis). Since
      /// the areas do not overlap, each is filled with a different opaque color.
      case stackedArea
      /// The data is plotted as a set of rectangular boxes (one box per series),
      /// with the boxes stacked vertically (the base of each box is the top of
      /// its predecessor, and the base of the first box is the x-axis). Since
      /// the boxes do not overlap, each is filled with a different opaque color.
      case stackedBar
      /// The data is plotted as a heatmap. The series being plotted must have a
      /// `DISTRIBUTION` value type. The value of each bucket in the distribution
      /// is displayed as a color. This type is not currently available in the
      /// Stackdriver Monitoring application.
      case heatmap
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .line: return 1
        case .stackedArea: return 2
        case .stackedBar: return 3
        case .heatmap: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "PLOT_TYPE_UNSPECIFIED"
        case .line: return "LINE"
        case .stackedArea: return "STACKED_AREA"
        case .stackedBar: return "STACKED_BAR"
        case .heatmap: return "HEATMAP"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PlotType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PLOT_TYPE_UNSPECIFIED": self = .unspecified
        case "LINE": self = .line
        case "STACKED_AREA": self = .stackedArea
        case "STACKED_BAR": self = .stackedBar
        case "HEATMAP": self = .heatmap
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PlotType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .line
        case 2: self = .stackedArea
        case 3: self = .stackedBar
        case 4: self = .heatmap
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .line: return try container.encode(1)
        case .stackedArea: return try container.encode(2)
        case .stackedBar: return try container.encode(3)
        case .heatmap: return try container.encode(4)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// An axis identifier.
    public enum TargetAxis: Codable, Equatable, Sendable {
      /// The target axis was not specified. Defaults to Y1.
      case unspecified
      /// The y_axis (the right axis of chart).
      case y1
      /// The y2_axis (the left axis of chart).
      case y2
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .y1: return 1
        case .y2: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TARGET_AXIS_UNSPECIFIED"
        case .y1: return "Y1"
        case .y2: return "Y2"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TargetAxis/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TARGET_AXIS_UNSPECIFIED": self = .unspecified
        case "Y1": self = .y1
        case "Y2": self = .y2
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TargetAxis/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .y1
        case 2: self = .y2
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .y1: return try container.encode(1)
        case .y2: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.XyChart.DataSet"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A chart axis.
  public struct Axis: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The label of the axis.
    public var label: Swift.String = Swift.String()

    /// The axis scale. By default, a linear scale is used.
    public var scale: XyChart.Axis.Scale = XyChart.Axis.Scale()

    /// Initialize a new instance of `Axis`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Axis().with { $0.label = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Types of scales used in axes.
    public enum Scale: Codable, Equatable, Sendable {
      /// Scale is unspecified. The view will default to `LINEAR`.
      case unspecified
      /// Linear scale.
      case linear
      /// Logarithmic scale (base 10).
      case log10
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .linear: return 1
        case .log10: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SCALE_UNSPECIFIED"
        case .linear: return "LINEAR"
        case .log10: return "LOG10"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Scale/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SCALE_UNSPECIFIED": self = .unspecified
        case "LINEAR": self = .linear
        case "LOG10": self = .log10
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Scale/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .linear
        case 2: self = .log10
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .linear: return try container.encode(1)
        case .log10: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.XyChart.Axis"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.XyChart"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
