// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// Manages Stackdriver dashboards. A dashboard is an arrangement of data display
/// widgets in a specific layout.
///
/// @Snippet(path: "DashboardsServiceQuickstart")
public class DashboardsServiceClient: Clients.DashboardsServiceProtocol {
  let inner: any Clients.DashboardsServiceStub

  /// Creates a new `DashboardsServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.DashboardsServiceStub = try Clients.DashboardsServiceTransport(options)
    inner = Clients.DashboardsServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DashboardsServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new custom dashboard. For examples on how you can use this API to
  /// create dashboards, see [Managing dashboards by
  /// API](https://cloud.google.com/monitoring/dashboards/api-dashboard). This
  /// method requires the `monitoring.dashboards.create` permission on the
  /// specified project. For more information about permissions, see [Cloud
  /// Identity and Access Management](https://cloud.google.com/iam).
  ///
  /// @Snippet(path: "DashboardsService_CreateDashboard")
  public func createDashboard(
    request: CreateDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
    try await self.inner.createDashboard(request: request, options: options)
  }

  /// Lists the existing dashboards.
  ///
  /// This method requires the `monitoring.dashboards.list` permission
  /// on the specified project. For more information, see
  /// [Cloud Identity and Access Management](https://cloud.google.com/iam).
  ///
  /// @Snippet(path: "DashboardsService_ListDashboards")
  public func listDashboards(
    request: ListDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse {
    try await self.inner.listDashboards(request: request, options: options)
  }

  /// Lists the existing dashboards.
  ///
  /// This method requires the `monitoring.dashboards.list` permission
  /// on the specified project. For more information, see
  /// [Cloud Identity and Access Management](https://cloud.google.com/iam).
  ///
  /// @Snippet(path: "DashboardsService_ListDashboards")
  public func listDashboards(
    byItem: ListDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Dashboard, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listDashboards(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Fetches a specific dashboard.
  ///
  /// This method requires the `monitoring.dashboards.get` permission
  /// on the specified dashboard. For more information, see
  /// [Cloud Identity and Access Management](https://cloud.google.com/iam).
  ///
  /// @Snippet(path: "DashboardsService_GetDashboard")
  public func getDashboard(
    request: GetDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
    try await self.inner.getDashboard(request: request, options: options)
  }

  /// Deletes an existing custom dashboard.
  ///
  /// This method requires the `monitoring.dashboards.delete` permission
  /// on the specified dashboard. For more information, see
  /// [Cloud Identity and Access Management](https://cloud.google.com/iam).
  ///
  /// @Snippet(path: "DashboardsService_DeleteDashboard")
  public func deleteDashboard(
    request: DeleteDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteDashboard(request: request, options: options)
  }

  /// Replaces an existing custom dashboard with a new definition.
  ///
  /// This method requires the `monitoring.dashboards.update` permission
  /// on the specified dashboard. For more information, see
  /// [Cloud Identity and Access Management](https://cloud.google.com/iam).
  ///
  /// @Snippet(path: "DashboardsService_UpdateDashboard")
  public func updateDashboard(
    request: UpdateDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
    try await self.inner.updateDashboard(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DashboardsServiceClient`.
  ///
  /// To mock `DashboardsServiceClient` change your functions to receive
  /// `some DashboardsServiceProtocol` or `any DashboardsServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DashboardsServiceProtocol {
    /// See `DashboardsServiceClient.createDashboard`.
    func createDashboard(request: CreateDashboardRequest) async throws
      -> GoogleCloudMonitoringDashboardV1.Dashboard

    /// See `DashboardsServiceClient.createDashboard`.
    func createDashboard(
      parent: Swift.String,
      dashboard: Dashboard?,
    ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard

    /// See `DashboardsServiceClient.listDashboards`.
    func listDashboards(request: ListDashboardsRequest) async throws
      -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse

    /// See `DashboardsServiceClient.listDashboards`.
    func listDashboards(
      byItem: ListDashboardsRequest
    ) throws -> any AsyncSequence<Dashboard, Swift.Error>

    /// See `DashboardsServiceClient.listDashboards`.
    func listDashboards(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Dashboard, Swift.Error>

    /// See `DashboardsServiceClient.getDashboard`.
    func getDashboard(request: GetDashboardRequest) async throws
      -> GoogleCloudMonitoringDashboardV1.Dashboard

    /// See `DashboardsServiceClient.getDashboard`.
    func getDashboard(
      name: Swift.String,
    ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard

    /// See `DashboardsServiceClient.deleteDashboard`.
    func deleteDashboard(request: DeleteDashboardRequest) async throws

    /// See `DashboardsServiceClient.deleteDashboard`.
    func deleteDashboard(
      name: Swift.String,
    ) async throws

    /// See `DashboardsServiceClient.updateDashboard`.
    func updateDashboard(request: UpdateDashboardRequest) async throws
      -> GoogleCloudMonitoringDashboardV1.Dashboard

    /// See `DashboardsServiceClient.createDashboard`.
    func createDashboard(
      request: CreateDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard

    /// See `DashboardsServiceClient.listDashboards`.
    func listDashboards(
      request: ListDashboardsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse

    /// See `DashboardsServiceClient.listDashboards`.
    func listDashboards(
      byItem: ListDashboardsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Dashboard, Swift.Error>

    /// See `DashboardsServiceClient.getDashboard`.
    func getDashboard(
      request: GetDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard

    /// See `DashboardsServiceClient.deleteDashboard`.
    func deleteDashboard(
      request: DeleteDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DashboardsServiceClient.updateDashboard`.
    func updateDashboard(
      request: UpdateDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard
  }
}

// Default implementations
extension Clients.DashboardsServiceProtocol {
  public func createDashboard(request: CreateDashboardRequest) async throws
    -> GoogleCloudMonitoringDashboardV1.Dashboard
  {
    try await self.createDashboard(request: request, options: .init())
  }

  public func createDashboard(
    request: CreateDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createDashboard(
    parent: Swift.String,
    dashboard: Dashboard?,
  ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
    let request = CreateDashboardRequest().with {
      $0.parent = parent
      $0.dashboard = dashboard
    }
    return try await self.createDashboard(request: request)
  }

  public func listDashboards(request: ListDashboardsRequest) async throws
    -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse
  {
    try await self.listDashboards(request: request, options: .init())
  }

  public func listDashboards(
    request: ListDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDashboards(
    byItem: ListDashboardsRequest
  ) throws -> any AsyncSequence<Dashboard, Swift.Error> {
    try self.listDashboards(byItem: byItem, options: .init())
  }

  public func listDashboards(
    byItem: ListDashboardsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Dashboard, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDashboards(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Dashboard, Swift.Error> {
    let request = ListDashboardsRequest().with {
      $0.parent = parent
    }
    return try self.listDashboards(byItem: request)
  }

  public func getDashboard(request: GetDashboardRequest) async throws
    -> GoogleCloudMonitoringDashboardV1.Dashboard
  {
    try await self.getDashboard(request: request, options: .init())
  }

  public func getDashboard(
    request: GetDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDashboard(
    name: Swift.String,
  ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
    let request = GetDashboardRequest().with {
      $0.name = name
    }
    return try await self.getDashboard(request: request)
  }

  public func deleteDashboard(request: DeleteDashboardRequest) async throws {
    try await self.deleteDashboard(request: request, options: .init())
  }

  public func deleteDashboard(
    request: DeleteDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteDashboard(
    name: Swift.String,
  ) async throws {
    let request = DeleteDashboardRequest().with {
      $0.name = name
    }
    try await self.deleteDashboard(request: request)
  }

  public func updateDashboard(request: UpdateDashboardRequest) async throws
    -> GoogleCloudMonitoringDashboardV1.Dashboard
  {
    try await self.updateDashboard(request: request, options: .init())
  }

  public func updateDashboard(
    request: UpdateDashboardRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
