// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class DashboardsServiceRetry: DashboardsServiceStub {
    let inner: any DashboardsServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any DashboardsServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createDashboard(
      request: CreateDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDashboardRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringDashboardV1.Dashboard
          in
          return try await self.inner.createDashboard(request: r, options: o)
        })
    }

    public func listDashboards(
      request: ListDashboardsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDashboardsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringDashboardV1.ListDashboardsResponse
          in
          return try await self.inner.listDashboards(request: r, options: o)
        })
    }

    public func getDashboard(
      request: GetDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDashboardRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringDashboardV1.Dashboard
          in
          return try await self.inner.getDashboard(request: r, options: o)
        })
    }

    public func deleteDashboard(
      request: DeleteDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDashboardRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDashboard(request: r, options: o)
        })
    }

    public func updateDashboard(
      request: UpdateDashboardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMonitoringDashboardV1.Dashboard {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDashboardRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMonitoringDashboardV1.Dashboard
          in
          return try await self.inner.updateDashboard(request: r, options: o)
        })
    }
  }
}
