// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A filter to reduce the amount of data charted in relevant widgets.
public struct DashboardFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The key for the label
  public var labelKey: Swift.String = Swift.String()

  /// The placeholder text that can be referenced in a filter string or MQL
  /// query. If omitted, the dashboard filter will be applied to all relevant
  /// widgets in the dashboard.
  public var templateVariable: Swift.String = Swift.String()

  /// The specified filter type
  public var filterType: DashboardFilter.FilterType = DashboardFilter.FilterType()

  /// The default value used in the filter comparison
  public var defaultValue: OneOf_DefaultValue? = nil

  /// Initialize a new instance of `DashboardFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DashboardFilter().with { $0.labelKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case labelKey = "labelKey"
    case templateVariable = "templateVariable"
    case stringValue = "stringValue"
    case filterType = "filterType"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.labelKey = try container.decode(Swift.String.self, forKey: .labelKey)
    self.templateVariable = try container.decode(Swift.String.self, forKey: .templateVariable)
    self.filterType = try container.decode(DashboardFilter.FilterType.self, forKey: .filterType)

    var defaultValue: OneOf_DefaultValue? = nil
    let defaultValueCheckAndSet = {
      if defaultValue != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'defaultValue'"))
      }
      defaultValue = $0
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try defaultValueCheckAndSet(.stringValue(stringValue))
    }
    self.defaultValue = defaultValue
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.labelKey, forKey: .labelKey)
    try container.encode(self.templateVariable, forKey: .templateVariable)
    try container.encode(self.filterType, forKey: .filterType)

    if let choice = self.defaultValue {
      switch choice {
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      }
    }
  }

  /// The type for the dashboard filter
  public enum FilterType: Codable, Equatable, Sendable {
    /// Filter type is unspecified. This is not valid in a well-formed request.
    case unspecified
    /// Filter on a resource label value
    case resourceLabel
    /// Filter on a metrics label value
    case metricLabel
    /// Filter on a user metadata label value
    case userMetadataLabel
    /// Filter on a system metadata label value
    case systemMetadataLabel
    /// Filter on a group id
    case group
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resourceLabel: return 1
      case .metricLabel: return 2
      case .userMetadataLabel: return 3
      case .systemMetadataLabel: return 4
      case .group: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FILTER_TYPE_UNSPECIFIED"
      case .resourceLabel: return "RESOURCE_LABEL"
      case .metricLabel: return "METRIC_LABEL"
      case .userMetadataLabel: return "USER_METADATA_LABEL"
      case .systemMetadataLabel: return "SYSTEM_METADATA_LABEL"
      case .group: return "GROUP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FilterType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FILTER_TYPE_UNSPECIFIED": self = .unspecified
      case "RESOURCE_LABEL": self = .resourceLabel
      case "METRIC_LABEL": self = .metricLabel
      case "USER_METADATA_LABEL": self = .userMetadataLabel
      case "SYSTEM_METADATA_LABEL": self = .systemMetadataLabel
      case "GROUP": self = .group
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FilterType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .resourceLabel
      case 2: self = .metricLabel
      case 3: self = .userMetadataLabel
      case 4: self = .systemMetadataLabel
      case 5: self = .group
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .resourceLabel: return try container.encode(1)
      case .metricLabel: return try container.encode(2)
      case .userMetadataLabel: return try container.encode(3)
      case .systemMetadataLabel: return try container.encode(4)
      case .group: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The default value used in the filter comparison
  public enum OneOf_DefaultValue: Codable, Equatable, Sendable {
    /// A variable-length string value.
    case stringValue(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.DashboardFilter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
