// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A widget that displays a list of error groups.
public struct ErrorReportingPanel: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the Google Cloud Platform project. Written
  /// as `projects/{projectID}` or `projects/{projectNumber}`, where
  /// `{projectID}` and `{projectNumber}` can be found in the
  /// [Google Cloud console](https://support.google.com/cloud/answer/6158840).
  ///
  /// Examples: `projects/my-project-123`, `projects/5551234`.
  public var projectNames: [Swift.String] = []

  /// An identifier of the service, such as the name of the
  /// executable, job, or Google App Engine service name. This field is expected
  /// to have a low number of values that are relatively stable over time, as
  /// opposed to `version`, which can be changed whenever new code is deployed.
  ///
  /// Contains the service name for error reports extracted from Google
  /// App Engine logs or `default` if the App Engine default service is used.
  public var services: [Swift.String] = []

  /// Represents the source code version that the developer provided,
  /// which could represent a version label or a Git SHA-1 hash, for example.
  /// For App Engine standard environment, the version is set to the version of
  /// the app.
  public var versions: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ErrorReportingPanel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ErrorReportingPanel().with { $0.projectNames = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let projectNames = CodingKeys(stringValue: "projectNames")
    static let services = CodingKeys(stringValue: "services")
    static let versions = CodingKeys(stringValue: "versions")

    static let _knownKeys: Set<Swift.String> = [
      "projectNames",
      "services",
      "versions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .projectNames) {
      self.projectNames = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .services) {
      self.services = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .versions) {
      self.versions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.projectNames, forKey: .projectNames)
    try container.encode(self.services, forKey: .services)
    try container.encode(self.versions, forKey: .versions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.ErrorReportingPanel"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
