// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleWKT

/// A widget that displays a list of incidents
public struct IncidentList: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The monitored resource for which incidents are listed.
  /// The resource doesn't need to be fully specified. That is, you can specify
  /// the resource type but not the values of the resource labels.
  /// The resource type and labels are used for filtering.
  public var monitoredResources: [GoogleApi.MonitoredResource] = []

  /// Optional. A list of alert policy names to filter the incident list by.
  /// Don't include the project ID prefix in the policy name. For
  /// example, use `alertPolicies/utilization`.
  public var policyNames: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `IncidentList`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IncidentList().with { $0.monitoredResources = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let monitoredResources = CodingKeys(stringValue: "monitoredResources")
    static let policyNames = CodingKeys(stringValue: "policyNames")

    static let _knownKeys: Set<Swift.String> = [
      "monitoredResources",
      "policyNames",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [GoogleApi.MonitoredResource].self, forKey: .monitoredResources)
    {
      self.monitoredResources = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .policyNames) {
      self.policyNames = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.monitoredResources, forKey: .monitoredResources)
    try container.encode(self.policyNames, forKey: .policyNames)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.IncidentList"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
