// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A widget that displays a stream of log.
public struct LogsPanel: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A filter that chooses which log entries to return.  See [Advanced Logs
  /// Queries](https://cloud.google.com/logging/docs/view/advanced-queries).
  /// Only log entries that match the filter are returned.  An empty filter
  /// matches all log entries.
  public var filter: Swift.String = Swift.String()

  /// The names of logging resources to collect logs for. Currently only projects
  /// are supported. If empty, the widget will default to the host project.
  public var resourceNames: [Swift.String] = []

  /// Initialize a new instance of `LogsPanel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogsPanel().with { $0.filter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.LogsPanel"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
