// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A mosaic layout divides the available space into a grid of blocks, and
/// overlays the grid with tiles. Unlike `GridLayout`, tiles may span multiple
/// grid blocks and can be placed at arbitrary locations in the grid.
public struct MosaicLayout: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The number of columns in the mosaic grid. The number of columns must be
  /// between 1 and 12, inclusive.
  public var columns: Swift.Int32 = Swift.Int32()

  /// The tiles to display.
  public var tiles: [MosaicLayout.Tile] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `MosaicLayout`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MosaicLayout().with { $0.columns = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let columns = CodingKeys(stringValue: "columns")
    static let tiles = CodingKeys(stringValue: "tiles")

    static let _knownKeys: Set<Swift.String> = [
      "columns",
      "tiles",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .columns) {
      self.columns = value
    }
    if let value = try container.decodeIfPresent([MosaicLayout.Tile].self, forKey: .tiles) {
      self.tiles = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.columns, forKey: .columns)
    try container.encode(self.tiles, forKey: .tiles)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A single tile in the mosaic. The placement and size of the tile are
  /// configurable.
  public struct Tile: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The zero-indexed position of the tile in grid blocks relative to the
    /// left edge of the grid. Tiles must be contained within the specified
    /// number of columns. `x_pos` cannot be negative.
    public var xPos: Swift.Int32 = Swift.Int32()

    /// The zero-indexed position of the tile in grid blocks relative to the
    /// top edge of the grid. `y_pos` cannot be negative.
    public var yPos: Swift.Int32 = Swift.Int32()

    /// The width of the tile, measured in grid blocks. Tiles must have a
    /// minimum width of 1.
    public var width: Swift.Int32 = Swift.Int32()

    /// The height of the tile, measured in grid blocks. Tiles must have a
    /// minimum height of 1.
    public var height: Swift.Int32 = Swift.Int32()

    /// The informational widget contained in the tile. For example an `XyChart`.
    public var widget: Widget? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Tile`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Tile().with { $0.xPos = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let xPos = CodingKeys(stringValue: "xPos")
      static let yPos = CodingKeys(stringValue: "yPos")
      static let width = CodingKeys(stringValue: "width")
      static let height = CodingKeys(stringValue: "height")
      static let widget = CodingKeys(stringValue: "widget")

      static let _knownKeys: Set<Swift.String> = [
        "xPos",
        "yPos",
        "width",
        "height",
        "widget",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .xPos) {
        self.xPos = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .yPos) {
        self.yPos = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .width) {
        self.width = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .height) {
        self.height = value
      }
      self.widget = try container.decodeIfPresent(Widget.self, forKey: .widget)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.xPos, forKey: .xPos)
      try container.encode(self.yPos, forKey: .yPos)
      try container.encode(self.width, forKey: .width)
      try container.encode(self.height, forKey: .height)
      try container.encodeIfPresent(self.widget, forKey: .widget)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.MosaicLayout.Tile"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.MosaicLayout"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
