// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A widget that displays timeseries data as a pie or a donut.
public struct PieChart: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The queries for the chart's data.
  public var dataSets: [PieChart.PieChartDataSet] = []

  /// Required. Indicates the visualization type for the PieChart.
  public var chartType: PieChart.PieChartType = PieChart.PieChartType()

  /// Optional. Indicates whether or not the pie chart should show slices' labels
  public var showLabels: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PieChart`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PieChart().with { $0.dataSets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let dataSets = CodingKeys(stringValue: "dataSets")
    static let chartType = CodingKeys(stringValue: "chartType")
    static let showLabels = CodingKeys(stringValue: "showLabels")

    static let _knownKeys: Set<Swift.String> = [
      "dataSets",
      "chartType",
      "showLabels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([PieChart.PieChartDataSet].self, forKey: .dataSets)
    {
      self.dataSets = value
    }
    if let value = try container.decodeIfPresent(PieChart.PieChartType.self, forKey: .chartType) {
      self.chartType = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .showLabels) {
      self.showLabels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dataSets, forKey: .dataSets)
    try container.encode(self.chartType, forKey: .chartType)
    try container.encode(self.showLabels, forKey: .showLabels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Groups a time series query definition.
  public struct PieChartDataSet: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The query for the PieChart. See,
    /// `google.monitoring.dashboard.v1.TimeSeriesQuery`.
    public var timeSeriesQuery: TimeSeriesQuery? = nil

    /// Optional. A template for the name of the slice. This name will be
    /// displayed in the legend and the tooltip of the pie chart. It replaces the
    /// auto-generated names for the slices. For example, if the template is set
    /// to
    /// `${resource.labels.zone}`, the zone's value will be used for the name
    /// instead of the default name.
    public var sliceNameTemplate: Swift.String = Swift.String()

    /// Optional. The lower bound on data point frequency for this data set,
    /// implemented by specifying the minimum alignment period to use in a time
    /// series query. For example, if the data is published once every 10
    /// minutes, the `min_alignment_period` should be at least 10 minutes. It
    /// would not make sense to fetch and align data at one minute intervals.
    public var minAlignmentPeriod: GoogleWKT.Duration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PieChartDataSet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PieChartDataSet().with { $0.timeSeriesQuery = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let timeSeriesQuery = CodingKeys(stringValue: "timeSeriesQuery")
      static let sliceNameTemplate = CodingKeys(stringValue: "sliceNameTemplate")
      static let minAlignmentPeriod = CodingKeys(stringValue: "minAlignmentPeriod")

      static let _knownKeys: Set<Swift.String> = [
        "timeSeriesQuery",
        "sliceNameTemplate",
        "minAlignmentPeriod",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.timeSeriesQuery = try container.decodeIfPresent(
        TimeSeriesQuery.self, forKey: .timeSeriesQuery)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sliceNameTemplate) {
        self.sliceNameTemplate = value
      }
      self.minAlignmentPeriod = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .minAlignmentPeriod)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.timeSeriesQuery, forKey: .timeSeriesQuery)
      try container.encode(self.sliceNameTemplate, forKey: .sliceNameTemplate)
      try container.encodeIfPresent(self.minAlignmentPeriod, forKey: .minAlignmentPeriod)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.PieChart.PieChartDataSet"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Types for the pie chart.
  public enum PieChartType: Codable, Equatable, Sendable {
    /// The zero value. No type specified. Do not use.
    case unspecified
    /// A Pie type PieChart.
    case pie
    /// Similar to PIE, but the DONUT type PieChart has a hole in the middle.
    case donut
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pie: return 1
      case .donut: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PIE_CHART_TYPE_UNSPECIFIED"
      case .pie: return "PIE"
      case .donut: return "DONUT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PieChartType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PIE_CHART_TYPE_UNSPECIFIED": self = .unspecified
      case "PIE": self = .pie
      case "DONUT": self = .donut
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PieChartType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pie
      case 2: self = .donut
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PIE_CHART_TYPE_UNSPECIFIED")
      case .pie: return try container.encode("PIE")
      case .donut: return try container.encode("DONUT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.PieChart"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
