// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A table that displays time series data.
public struct TimeSeriesTable: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The data displayed in this table.
  public var dataSets: [TimeSeriesTable.TableDataSet] = []

  /// Optional. Store rendering strategy
  public var metricVisualization: TimeSeriesTable.MetricVisualization =
    TimeSeriesTable.MetricVisualization()

  /// Optional. The list of the persistent column settings for the table.
  public var columnSettings: [TimeSeriesTable.ColumnSettings] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TimeSeriesTable`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeSeriesTable().with { $0.dataSets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let dataSets = CodingKeys(stringValue: "dataSets")
    static let metricVisualization = CodingKeys(stringValue: "metricVisualization")
    static let columnSettings = CodingKeys(stringValue: "columnSettings")

    static let _knownKeys: Set<Swift.String> = [
      "dataSets",
      "metricVisualization",
      "columnSettings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [TimeSeriesTable.TableDataSet].self, forKey: .dataSets)
    {
      self.dataSets = value
    }
    if let value = try container.decodeIfPresent(
      TimeSeriesTable.MetricVisualization.self, forKey: .metricVisualization)
    {
      self.metricVisualization = value
    }
    if let value = try container.decodeIfPresent(
      [TimeSeriesTable.ColumnSettings].self, forKey: .columnSettings)
    {
      self.columnSettings = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dataSets, forKey: .dataSets)
    try container.encode(self.metricVisualization, forKey: .metricVisualization)
    try container.encode(self.columnSettings, forKey: .columnSettings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Groups a time series query definition with table options.
  public struct TableDataSet: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Fields for querying time series data from the
    /// Stackdriver metrics API.
    public var timeSeriesQuery: TimeSeriesQuery? = nil

    /// Optional. A template string for naming `TimeSeries` in the resulting data
    /// set. This should be a string with interpolations of the form
    /// `${label_name}`, which will resolve to the label's value i.e.
    /// "${resource.labels.project_id}."
    public var tableTemplate: Swift.String = Swift.String()

    /// Optional. The lower bound on data point frequency for this data set,
    /// implemented by specifying the minimum alignment period to use in a time
    /// series query For example, if the data is published once every 10 minutes,
    /// the `min_alignment_period` should be at least 10 minutes. It would not
    /// make sense to fetch and align data at one minute intervals.
    public var minAlignmentPeriod: GoogleWKT.Duration? = nil

    /// Optional. Table display options for configuring how the table is
    /// rendered.
    public var tableDisplayOptions: TableDisplayOptions? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TableDataSet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TableDataSet().with { $0.timeSeriesQuery = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let timeSeriesQuery = CodingKeys(stringValue: "timeSeriesQuery")
      static let tableTemplate = CodingKeys(stringValue: "tableTemplate")
      static let minAlignmentPeriod = CodingKeys(stringValue: "minAlignmentPeriod")
      static let tableDisplayOptions = CodingKeys(stringValue: "tableDisplayOptions")

      static let _knownKeys: Set<Swift.String> = [
        "timeSeriesQuery",
        "tableTemplate",
        "minAlignmentPeriod",
        "tableDisplayOptions",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.timeSeriesQuery = try container.decodeIfPresent(
        TimeSeriesQuery.self, forKey: .timeSeriesQuery)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tableTemplate) {
        self.tableTemplate = value
      }
      self.minAlignmentPeriod = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .minAlignmentPeriod)
      self.tableDisplayOptions = try container.decodeIfPresent(
        TableDisplayOptions.self, forKey: .tableDisplayOptions)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.timeSeriesQuery, forKey: .timeSeriesQuery)
      try container.encode(self.tableTemplate, forKey: .tableTemplate)
      try container.encodeIfPresent(self.minAlignmentPeriod, forKey: .minAlignmentPeriod)
      try container.encodeIfPresent(self.tableDisplayOptions, forKey: .tableDisplayOptions)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.TimeSeriesTable.TableDataSet"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The persistent settings for a table's columns.
  public struct ColumnSettings: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The id of the column.
    public var column: Swift.String = Swift.String()

    /// Required. Whether the column should be visible on page load.
    public var visible: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ColumnSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ColumnSettings().with { $0.column = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let column = CodingKeys(stringValue: "column")
      static let visible = CodingKeys(stringValue: "visible")

      static let _knownKeys: Set<Swift.String> = [
        "column",
        "visible",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .column) {
        self.column = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .visible) {
        self.visible = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.column, forKey: .column)
      try container.encode(self.visible, forKey: .visible)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.monitoring.dashboard.v1.TimeSeriesTable.ColumnSettings"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Enum for metric metric_visualization
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum MetricVisualization: Codable, Equatable, Sendable {
    /// Unspecified state
    case unspecified
    /// Default text rendering
    case number
    /// Horizontal bar rendering
    case bar
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .number: return 1
      case .bar: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "METRIC_VISUALIZATION_UNSPECIFIED"
      case .number: return "NUMBER"
      case .bar: return "BAR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MetricVisualization/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "METRIC_VISUALIZATION_UNSPECIFIED": self = .unspecified
      case "NUMBER": self = .number
      case "BAR": self = .bar
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MetricVisualization/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .number
      case 2: self = .bar
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("METRIC_VISUALIZATION_UNSPECIFIED")
      case .number: return try container.encode("NUMBER")
      case .bar: return try container.encode("BAR")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.TimeSeriesTable"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
