// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A filter that defines a subset of time series data that is displayed in a
/// widget. Time series data is fetched using the
/// [`ListTimeSeries`](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list)
/// method.
public struct TimeSeriesFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The [monitoring
  /// filter](https://cloud.google.com/monitoring/api/v3/filters) that identifies
  /// the metric types, resources, and projects to query.
  public var filter: Swift.String = Swift.String()

  /// By default, the raw time series data is returned.
  /// Use this field to combine multiple time series for different views of the
  /// data.
  public var aggregation: Aggregation? = nil

  /// Apply a second aggregation after `aggregation` is applied.
  public var secondaryAggregation: Aggregation? = nil

  /// Selects an optional time series filter.
  public var outputFilter: OneOf_OutputFilter? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TimeSeriesFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeSeriesFilter().with { $0.filter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let filter = CodingKeys(stringValue: "filter")
    static let aggregation = CodingKeys(stringValue: "aggregation")
    static let secondaryAggregation = CodingKeys(stringValue: "secondaryAggregation")
    static let pickTimeSeriesFilter = CodingKeys(stringValue: "pickTimeSeriesFilter")
    static let statisticalTimeSeriesFilter = CodingKeys(stringValue: "statisticalTimeSeriesFilter")

    static let _knownKeys: Set<Swift.String> = [
      "filter",
      "aggregation",
      "secondaryAggregation",
      "pickTimeSeriesFilter",
      "statisticalTimeSeriesFilter",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    self.aggregation = try container.decodeIfPresent(Aggregation.self, forKey: .aggregation)
    self.secondaryAggregation = try container.decodeIfPresent(
      Aggregation.self, forKey: .secondaryAggregation)

    var outputFilter: OneOf_OutputFilter? = nil
    let outputFilterCheckAndSet = {
      if outputFilter != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'outputFilter'"))
      }
      outputFilter = $0
    }
    if let pickTimeSeriesFilter = try container.decodeIfPresent(
      PickTimeSeriesFilter?.self, forKey: .pickTimeSeriesFilter)
    {
      try outputFilterCheckAndSet(.pickTimeSeriesFilter(pickTimeSeriesFilter))
    }
    if let statisticalTimeSeriesFilter = try container.decodeIfPresent(
      StatisticalTimeSeriesFilter?.self, forKey: .statisticalTimeSeriesFilter)
    {
      try outputFilterCheckAndSet(.statisticalTimeSeriesFilter(statisticalTimeSeriesFilter))
    }
    self.outputFilter = outputFilter
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.filter, forKey: .filter)
    try container.encodeIfPresent(self.aggregation, forKey: .aggregation)
    try container.encodeIfPresent(self.secondaryAggregation, forKey: .secondaryAggregation)

    if let choice = self.outputFilter {
      switch choice {
      case .pickTimeSeriesFilter(let value):
        try container.encode(value, forKey: .pickTimeSeriesFilter)
      case .statisticalTimeSeriesFilter(let value):
        try container.encode(value, forKey: .statisticalTimeSeriesFilter)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Selects an optional time series filter.
  public enum OneOf_OutputFilter: Codable, Equatable, Sendable {
    /// Ranking based time series filter.
    indirect case pickTimeSeriesFilter(PickTimeSeriesFilter?)
    /// Statistics based time series filter.
    /// Note: This field is deprecated and completely ignored by the API.
    @available(*, deprecated)
    indirect case statisticalTimeSeriesFilter(StatisticalTimeSeriesFilter?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.monitoring.dashboard.v1.TimeSeriesFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
